-- This file used to drop and recreate the news table.
-- That reset has been removed so it cannot wipe production.
--
-- Apply the idempotent migration instead:
--   supabase/migrations/20261006120000_news_public_read.sql
--
-- It creates the table only if missing, dedupes links, and leaves
-- anonymous users with read-only access.
