name = "world-news-api"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "0a88b7bd7c06bb9ba3d859567cad6d04"

[triggers]
crons = ["*/15 * * * *"]

[env.production]
name = "world-news-api"
# Service key fallback 寫在 index.js 裡，CF 載入時自動加密
