// Regenerates shared/s2hkMap.ts from OpenCC (Simplified → Traditional, first candidate + word fixes). Dev-only; the 1 MB OpenCC bundle is not shipped.
//   npm i --no-save opencc-js && node scripts/gen-s2hk.mjs
import { writeFileSync } from 'node:fs';
import * as OpenCC from 'opencc-js';
import STCharacters from 'opencc-js/dict/STCharacters';

// Standard Traditional forms (說, 裡/裏 as OpenCC gives) to match the rest of the site.
const convert = OpenCC.Converter({ from: 'cn', to: 'hk' });
let pairs = '';
let count = 0;
// Characters Hong Kong text keeps as-is (香港電台, 干預, 麵 only via word fixes, 關係 via word fixes).
const KEEP = new Set([...'台干面系只']);
for (const entry of STCharacters.split('|')) {
  const [s, t] = entry.split(' ');
  if (KEEP.has(s)) continue;
  // BMP only so the pair string stays two UTF-16 units per entry.
  if (!s || !t || s === t || s.length !== 1 || t.length !== 1) continue;
  pairs += s + t;
  count += 1;
}
// Words where the one-character default is wrong. Checked against OpenCC phrase output.
const words = [
  '头发', '理发', '发型', '白发', '皇后', '干净', '干燥', '饼干', '干部', '干事', '能干', '树干', '面条', '面包', '方便面', '拉面',
  '只有', '只是', '只要', '一只', '两只', '系统', '关系', '联系', '体系', '里面', '公里', '这里', '哪里', '范围', '规范', '模范',
  '复杂', '复习', '恢复', '答复', '重复', '回复', '台风', '台湾', '舞台', '平台', '后来', '以后', '最后', '前后', '钟表', '时钟',
  '准备', '标准', '批准', '制造', '控制', '制度', '历史', '经历', '日历', '冲突', '冲击', '获得', '收获', '松树', '放松', '出租',
  '尽管', '尽量', '于是', '由于', '征收', '特征', '余额', '其余', '云南', '游戏', '旅游', '注意', '注册', '赞同', '称赞', '丑闻',
  '借鉴', '凶手', '卷入', '试卷', '划分', '计划', '采访', '采取', '谷歌', '山谷', '发表', '发布', '发展', '出发', '头条',
];
const map = new Map();
for (let i = 0; i < pairs.length; i += 2) map.set(pairs[i], pairs[i + 1]);
const byChar = (w) => [...w].map((c) => map.get(c) ?? c).join('');
const fixes = words.map((w) => [w, convert(w)]).filter(([w, t]) => t !== byChar(w));
writeFileSync('shared/s2hkMap.ts', `// Generated by scripts/gen-s2hk.mjs from OpenCC. ${count} characters, ${fixes.length} word fixes.\n` +
  `export const S2HK_CHARS = ${JSON.stringify(pairs)};\n` +
  `export const S2HK_WORDS: [string, string][] = ${JSON.stringify(fixes)};\n`);
console.log(count, fixes.length, fixes);
